import type { AgentContext, ToolDefinition, ToolExecutionServices } from '@agnes/agent-core';
import { buildResearchPrompt } from '@agnes/prompts';
import type { ResearchReportOutput, Source } from './types.js';

function parseSources(raw: unknown): Source[] {
  if (!raw) return [];

  if (Array.isArray(raw)) {
    return raw.filter(isSource);
  }

  if (typeof raw === 'object') {
    const record = raw as Record<string, unknown>;
    if (Array.isArray(record.sources)) {
      return record.sources.filter(isSource);
    }
  }

  return [];
}

function isSource(value: unknown): value is Source {
  if (!value || typeof value !== 'object') return false;
  const s = value as Record<string, unknown>;
  return (
    typeof s.id === 'string' &&
    typeof s.title === 'string' &&
    typeof s.url === 'string' &&
    typeof s.snippet === 'string'
  );
}

function cite(sources: Source[], ids: string[]): string {
  const valid = ids.filter((id) => sources.some((s) => s.id === id));
  return valid.length ? valid.map((id) => `[${id}]`).join('') : '(source unavailable)';
}

function reportFromSources(topic: string, title: string, sources: Source[]): ResearchReportOutput {
  const topSources = sources.slice(0, 5);
  const fallbackNotice = sources.some((s) => s.url.includes('agnes.local'))
    ? '> Note: live search was unavailable, so this report uses explicit fallback context for demo continuity. Replace it with live search results before production use.\n\n'
    : '';

  const findings = topSources
    .map((s) => `- ${s.snippet} ${cite(sources, [s.id])}`)
    .join('\n');

  const sourceIndex = topSources
    .map((s) => `- **${s.id}** - [${s.title}](${s.url})\n  ${s.snippet}`)
    .join('\n');

  const markdown = `# ${title}

${fallbackNotice}## 执行摘要

围绕 **${topic}**，当前来源显示：相关 Agent 产品能力正在从单点问答转向可规划、可调用工具、可保存上下文和可预览产物的工作台形态。以下判断严格基于本次检索来源，未确认的信息会保留为风险或待验证项。

## 关键发现

${findings}

## 产品与工程含义

- Agent 工作台需要同时覆盖路由、规划、工具执行、上下文记忆、Trace、产物预览和恢复能力。${cite(sources, ['S2'])}
- 验收不应只看静态页面，而要能解释每一步工具为什么被调用、产物从哪里来、失败如何恢复。${cite(sources, ['S3'])}
- 当实时检索不可用时，系统应显式标注降级，而不是把 fallback 伪装成真实来源。${cite(sources, ['S1'])}

## 建议路线

- 主 Agent 保持快速响应，长任务进入异步 workflow。
- 每个节点写入 checkpoint，支持中断后恢复。
- 会话记忆和工具记录进入数据库/云存储，避免刷新或重启后丢上下文。
- 报告中明确区分真实检索、模型生成和降级 fallback。

## 风险与待验证

- 来源数量和时效性会直接影响结论可信度。
- 若外部搜索 API 未配置，当前报告只能作为演示连续性的样例。
- 涉及市场规模、政策、融资等高变动事实时，需要补充实时来源。

## 来源索引

${sourceIndex}

---
Generated by Agnes Agent Workspace.
`;

  return { markdown, title };
}

export const researchReportTool: ToolDefinition = {
  name: 'research_report',
  description:
    'Generate a structured Markdown research report from a topic and cited sources. Uses [S1] citation format and avoids unsupported claims.',
  inputSchema: {
    type: 'object',
    properties: {
      topic: { type: 'string', description: 'Report topic' },
      sources: {
        type: 'array',
        description: 'Source list from web_search (id, title, url, snippet)',
      },
    },
    required: ['topic', 'sources'],
  },
  async execute(input, ctx: AgentContext, services?: ToolExecutionServices) {
    const topic = String(input.topic ?? ctx.task.userInput).trim();
    if (!topic) {
      return { success: false, output: null, error: 'research_report requires a topic' };
    }

    const sources = parseSources(input.sources);
    if (sources.length === 0) {
      return {
        success: false,
        output: null,
        error: 'research_report requires at least one source from web_search',
      };
    }

    const title = `${topic} Research Report`;

    if (services?.generateText) {
      const llmReport = await buildReportWithModel(topic, title, sources, services);
      if (llmReport) {
        return { success: true, output: llmReport };
      }
    }

    return { success: true, output: reportFromSources(topic, title, sources) };
  },
};

async function buildReportWithModel(
  topic: string,
  title: string,
  sources: Source[],
  services: ToolExecutionServices,
): Promise<ResearchReportOutput | null> {
  if (!services.generateText) return null;

  const sourceIds = sources.map((s) => s.id);
  const sourcesBlock = sources
    .map((s) => `${s.id}: ${s.title}\nURL: ${s.url}\nSnippet: ${s.snippet}`)
    .join('\n\n');

  try {
    const content = await services.generateText(
      [
        {
          role: 'system',
          content: buildResearchPrompt({ topic, sourceIds }),
        },
        {
          role: 'user',
          content: `Write a research report in Markdown.\n\nTopic: ${topic}\n\nSources:\n${sourcesBlock}\n\nOnly output the Markdown report body, starting with a # heading.`,
        },
      ],
      { temperature: 0.3, maxTokens: 4000 },
    );

    const markdown = content.trim();
    if (!markdown || !/^#\s+/m.test(markdown)) return null;

    const heading = markdown.match(/^#\s+(.+)$/m)?.[1]?.trim();
    return {
      markdown,
      title: heading || title,
    };
  } catch {
    return null;
  }
}
